CREATE TABLE "FOOTSTATS"."FOOTSTATS_STAGING_PLAYERSTATS_BRASILEIRAO" 
(	
	"Player" CLOB COLLATE "USING_NLS_COMP", 
	"Nation" CLOB COLLATE "USING_NLS_COMP", 
	"Pos" CLOB COLLATE "USING_NLS_COMP", 
	"Squad" CLOB COLLATE "USING_NLS_COMP", 
	"Age" CLOB COLLATE "USING_NLS_COMP", 
	"Born" CLOB COLLATE "USING_NLS_COMP", 
	"MP" CLOB COLLATE "USING_NLS_COMP", 
	"Starts" CLOB COLLATE "USING_NLS_COMP", 
	"Min" CLOB COLLATE "USING_NLS_COMP", 
	"90s" CLOB COLLATE "USING_NLS_COMP", 
	"Gls" CLOB COLLATE "USING_NLS_COMP", 
	"Ast" CLOB COLLATE "USING_NLS_COMP", 
	"G+A" CLOB COLLATE "USING_NLS_COMP", 
	"G-PK" CLOB COLLATE "USING_NLS_COMP", 
	"PK" CLOB COLLATE "USING_NLS_COMP", 
	"PKatt" CLOB COLLATE "USING_NLS_COMP", 
	"CrdY" CLOB COLLATE "USING_NLS_COMP", 
	"CrdR" CLOB COLLATE "USING_NLS_COMP", 
	"xG" CLOB COLLATE "USING_NLS_COMP", 
	"npxG" CLOB COLLATE "USING_NLS_COMP", 
	"xAG" CLOB COLLATE "USING_NLS_COMP", 
	"npxG+xAG" CLOB COLLATE "USING_NLS_COMP", 
	"PrgC" CLOB COLLATE "USING_NLS_COMP", 
	"PrgP" CLOB COLLATE "USING_NLS_COMP", 
	"PrgR" CLOB COLLATE "USING_NLS_COMP", 
	"Gls.1" CLOB COLLATE "USING_NLS_COMP", 
	"Ast.1" CLOB COLLATE "USING_NLS_COMP", 
	"G+A.1" CLOB COLLATE "USING_NLS_COMP", 
	"G-PK.1" CLOB COLLATE "USING_NLS_COMP", 
	"G+A-PK" CLOB COLLATE "USING_NLS_COMP", 
	"xG.1" CLOB COLLATE "USING_NLS_COMP", 
	"xAG.1" CLOB COLLATE "USING_NLS_COMP", 
	"xG+xAG" CLOB COLLATE "USING_NLS_COMP", 
	"npxG.1" CLOB COLLATE "USING_NLS_COMP", 
	"npxG+xAG.1" CLOB COLLATE "USING_NLS_COMP", 
	"CREATED_DATE" TIMESTAMP (6) WITH TIME ZONE
)  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
	PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
	STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "DATA" 
 LOB ("Player") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("Nation") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("Pos") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("Squad") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("Age") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("Born") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("MP") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("Starts") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("Min") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("90s") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("Gls") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("Ast") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("G+A") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("G-PK") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PK") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PKatt") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("CrdY") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("CrdR") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("xG") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("npxG") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("xAG") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("npxG+xAG") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PrgC") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PrgP") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PrgR") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("Gls.1") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("Ast.1") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("G+A.1") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("G-PK.1") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("G+A-PK") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("xG.1") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("xAG.1") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("xG+xAG") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("npxG.1") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("npxG+xAG.1") STORE AS SECUREFILE (
	TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
	NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
	STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
